apiVersion: v1
kind: ConfigMap
metadata:
  name: apmserver-config
  namespace: {{ .Values.common.namespace.apmserver }}
data:
{{- $files := .Files }}
{{- range tuple "apm-server.yml" }}
{{ . | indent 2}}: |-
{{ $files.Get (print "config/" .) | indent 4 }}
{{- end }}
