apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: {{ .Values.common.namespace.elasticsearch }}
data:
{{- $files := .Files }}
{{- range tuple "elasticsearch.yml" "jvm.options" "log4j2.properties" }}
{{ . | indent 2}}: |-
{{ $files.Get (print "config/" .) | indent 4 }}
{{- end }}
