apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-client
  labels:
    component: {{ template "fullname" . }}
    role: client
{{- $_ := set (.Values.client) "role" "client" }}
{{- $_ := set (.Values.client) "Global" . }}
spec:
{{ include "node.spec" .Values.client | indent 2 }}
