apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-client
  namespace: {{ .Values.common.namespace.elasticsearch }}
  labels:
    component: elasticsearch
    role: client
{{- $_ := set (.Values.client) "role" "client" }}
{{- $_ := set (.Values.client) "Global" . }}
spec:
{{ include "node.spec" .Values.client | indent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Values.common.namespace.elasticsearch }}
  labels:
    component: elasticsearch
    role: client
spec:
  type: {{ .Values.service.type }}
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: 9200
    protocol: TCP
  - name: transport
    port: {{ .Values.service.transportPort }}
    targetPort: 9300
    protocol: TCP
