apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}-data
  labels:
    component: {{ template "fullname" . }}
    role: data
spec:
  serviceName: {{ template "fullname" . }}-data-svc
  updateStrategy:
    type: RollingUpdate
  replicas: {{ .Values.data.replicas }}
  template:
    metadata:
      labels:
        component: {{ template "fullname" . }}
        role: data
    spec:
      securityContext:
        fsGroup: 1000
      {{- if  .Values.data.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.data.nodeSelector }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
    {{- if eq .Values.data.antiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  component: {{ template "fullname" . }}
                  role: data
      {{- else if eq .Values.data.antiAffinity "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  component: {{ template "fullname" . }}
                  role: data
      {{- end }}
      containers:
      - name: es-data
        securityContext:
          privileged: true
          runAsUser: 1000
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: "{{ .Values.common.image.elasticsearch }}:{{ .Values.common.image.tag }}"
        args:
          - sh
          - -c
          - |
            if [ ! -z "${ES_PLUGINS_INSTALL}" ]; then
              OLDIFS=$IFS
              IFS=','
              for plugin in ${ES_PLUGINS_INSTALL}; do
                if ! bin/elasticsearch-plugin list | grep -qs ${plugin}; then
                  until bin/elasticsearch-plugin install --batch ${plugin}; do
                    echo "failed to install ${plugin}, retrying in 3s"
                    sleep 3
                  done
                fi
              done
              IFS=$OLDIFS
            fi
            bin/elasticsearch
        resources:
          requests:
            memory: {{ .Values.data.memory.request }}
            cpu: {{ .Values.data.cpu.request }}
          limits:
            memory: {{ .Values.data.memory.limit }}
            cpu: {{ .Values.data.cpu.limit }}
        imagePullPolicy: {{ .Values.common.image.pullPolicy }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DISCOVERY_SERVICE
          value: {{ template "fullname" . }}-discovery
        {{- range $key, $value :=  .Values.common.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value :=  .Values.data.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: {{ template "fullname" . }}-storage
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: config
          mountPath: /usr/share/elasticsearch/config/jvm.options
          subPath: jvm.options
        - name: config
          mountPath: /usr/share/elasticsearch/config/log4j2.properties
          subPath: log4j2.properties
      volumes:
        - name: config
          configMap:
            name: {{ template "fullname" . }}-es-config
            items:
            - key: elasticsearch.yml
              path: elasticsearch.yml
            - key: jvm.options
              path: jvm.options
            - key: log4j2.properties
              path: log4j2.properties
  volumeClaimTemplates:
  - metadata:
      name: {{ template "fullname" . }}-storage
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: {{ template "fullname" . }}-storage-class
      resources:
        requests:
          storage: {{ .Values.data.storage }}
