apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}-data
  labels:
    component: {{ template "fullname" . }}
    role: data
spec:
  serviceName: {{ template "fullname" . }}-data-svc
  updateStrategy:
    type: RollingUpdate
  {{- $_ := set (.Values.data) "role" "data" }}
  {{- $_ := set (.Values.data) "Global" . }}
{{ include "node.spec" .Values.data | indent 2 }}
  volumeClaimTemplates:
  - metadata:
      name: {{ template "fullname" . }}-storage
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: {{ template "fullname" . }}-storage-class
      resources:
        requests:
          storage: {{ .Values.data.storage }}
