apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch-data
  namespace: {{ .Values.common.namespace.elasticsearch }}
  labels:
    component: elasticsearch
    role: data
spec:
  serviceName: elasticsearch-data-svc
  updateStrategy:
    type: RollingUpdate
  {{- $_ := set (.Values.data) "role" "data" }}
  {{- $_ := set (.Values.data) "Global" . }}
{{ include "node.spec" .Values.data | indent 2 }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: elasticsearch-data-storage-class
      resources:
        requests:
          storage: {{ .Values.data.storage }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elasticsearch-data-storage-class
  namespace: {{ .Values.common.namespace.elasticsearch }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data-svc
  namespace: {{ .Values.common.namespace.elasticsearch }}
  labels:
    component: elasticsearch
    role: data
spec:
  ports:
  - port: 9300
    name: transport
  clusterIP: None
  selector:
    component: elasticsearch
    role: data
