apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}-data
  labels:
    component: {{ template "fullname" . }}
    role: data
spec:
  serviceName: {{ template "fullname" . }}-data-svc
  updateStrategy:
    type: RollingUpdate
  {{- $_ := set (.Values.data) "role" "data" }}
  {{- $_ := set (.Values.data) "Global" . }}
{{ include "node.spec" .Values.data | indent 2 }}
  volumeClaimTemplates:
  - metadata:
      name: {{ template "fullname" . }}-storage
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: {{ template "fullname" . }}-es-data-storage-class
      resources:
        requests:
          storage: {{ .Values.data.storage }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ template "fullname" . }}-es-data-storage-class
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-data-svc
  labels:
    component: {{ template "fullname" . }}
    role: data
spec:
  ports:
  - port: 9300
    name: transport
  clusterIP: None
  selector:
    component: {{ template "fullname" . }}
    role: data
