apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-master
  namespace: {{ .Values.common.namespace.elasticsearch }}
  labels:
    component: elasticsearch
    role: master
{{- $_ := set (.Values.master) "role" "master" }}
{{- $_ := set (.Values.master) "Global" . }}
spec:
{{ include "node.spec" .Values.master | indent 2 }}
