apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-master
  labels:
    component: {{ template "fullname" . }}
    role: master
{{- $_ := set (.Values.master) "role" "master" }}
{{- $_ := set (.Values.master) "Global" . }}
spec:
{{ include "node.spec" .Values.master | indent 2 }}
