kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: {{ template "fullname" . }}-storage-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
