kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-storage
  labels:
    component: {{ template "fullname" . }}
    role: storage
spec:
  storageClassName: manual
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: elasticsearch-storage-test-1
    fsType: ext4
