apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: {{ .Values.common.namespace.kibana }}
  labels:
    component: elasticsearch
    role: kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: kibana
    spec:
      {{- if  .Values.kibana.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.kibana.nodeSelector }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
      containers:
      - name: kibana
        image: "{{ .Values.common.image.kibana }}:{{ .Values.common.image.tag }}"
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch.{{ .Values.common.namespace.elasticsearch }}:9200
        {{- range $key, $value :=  .Values.common.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value :=  .Values.kibana.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
          requests:
            memory: {{ .Values.kibana.memory.request }}
            cpu: {{ .Values.kibana.cpu.request }}
          limits:
            memory: {{ .Values.kibana.memory.limit }}
            cpu: {{ .Values.kibana.cpu.limit }}
        ports:
        - containerPort: 5601
          name: kibana
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{ .Values.common.namespace.kibana }}
  labels:
    component: elasticsearch
    role: kibana
spec:
  type: LoadBalancer
  selector:
    component: elasticsearch
    role: kibana
  ports:
  - name: http
    port: 80
    targetPort: 5601
    protocol: TCP
