apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-kibana
  namespace: default
  labels:
    component: {{ template "fullname" . }}-kibana
spec:
  selector:
    component: {{ template "fullname" . }}-kibana
    role: client
  ports:
  - name: http
    port: 80
    targetPort: 5601
    protocol: TCP
