apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-kibana
  labels:
    component: {{ template "fullname" . }}-kibana
    role: kibana
spec:
  type: LoadBalancer
  selector:
    component: {{ template "fullname" . }}-kibana
    role: kibana
  ports:
  - name: http
    port: 80
    targetPort: 5601
    protocol: TCP
