apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-kibana
  namespace: default
  labels:
    component: {{ template "fullname" . }}-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
     component: {{ template "fullname" . }}-kibana
  template:
    metadata:
      labels:
        component: {{ template "fullname" . }}-kibana
    spec:
      containers:
      - name: {{ template "fullname" . }}-kibana
        image: cfontes/kibana-xpack-less:5.5.0
        env:
        - name: CLUSTER_NAME
          value: {{ .Values.common.env.CLUSTER_NAME }}
        resources:
          requests:
            memory: {{ .Values.kibana.memory.request }}
            cpu: {{ .Values.kibana.cpu.request }}
          limits:
            memory: {{ .Values.kibana.memory.limit }}
            cpu: {{ .Values.kibana.cpu.limit }}
        ports:
        - containerPort: 5601
          name: kibana
          protocol: TCP
